version: '3'

services:
    symfony:
        build: .
        working_dir: /var/dev
        command: vendor/bin/server watch 0.0.0.0:8080 --adapter=App\\AppKernelAdapter
        ports:
            - 8080:8080
        volumes:
            - .:/var/dev
